name: Deploy production

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm ci
          npm test
        env:
          CI: true

  pre-deploy:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Clear the app dir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/krabicka
            pm2 stop krabickaBot
            rm -rf !(ecosystem.config.js)

  deploy:
    needs: [pre-deploy]
    runs-on: ubuntu-latest

    steps:
      - run: npm ci
      - run: npm run build
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          SOURCE: "dist/"

  post-deploy:
    needs: [deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Start the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pm2 start krabickaBot
